language: python

python:
  - "3.9"


cache:
  bundler: true
  directories:
    - $HOME/.pytest_cache
    - $HOME/.cache/pip
    - $HOME/docker

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

addons:
  apt:
    packages:
      - net-tools
